[tool.poetry]
name = "nextassist"
package-mode = false

[tool.poetry.dependencies]
python = "3.11.11"
streamlit = "^1.41.1"
python-dotenv = "^1.0.1"
snowflake-core = "^1.0.2"
snowflake-snowpark-python = "^1.26.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
